spring.datasource.url=jdbc:mysql://localhost:3306/visiongo_db
spring.datasource.username=root
spring.datasource.password=tuapassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
jwt.secret=visiongo_secret_key_2024
jwt.expiration=86400000
